/**
 * @fileoverview gRPC-Web generated client stub for api.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: focus_v1alpha1.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as focus_v1alpha1_pb from './focus_v1alpha1_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb';


export class FocusClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorversion = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/version',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_wrappers_pb.StringValue,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_wrappers_pb.StringValue.deserializeBinary
  );

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_wrappers_pb.StringValue>;

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void): grpcWeb.ClientReadableStream<google_protobuf_wrappers_pb.StringValue>;

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/version',
        request,
        metadata || {},
        this.methodDescriptorversion,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/version',
    request,
    metadata || {},
    this.methodDescriptorversion);
  }

  methodDescriptorgetUser = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/getUser',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    focus_v1alpha1_pb.User,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.User.deserializeBinary
  );

  getUser(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.User>;

  getUser(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.User) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.User>;

  getUser(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/getUser',
        request,
        metadata || {},
        this.methodDescriptorgetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/getUser',
    request,
    metadata || {},
    this.methodDescriptorgetUser);
  }

  methodDescriptoraddCard = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/addCard',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.AddCardReq,
    focus_v1alpha1_pb.Card,
    (request: focus_v1alpha1_pb.AddCardReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Card.deserializeBinary
  );

  addCard(
    request: focus_v1alpha1_pb.AddCardReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Card>;

  addCard(
    request: focus_v1alpha1_pb.AddCardReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Card>;

  addCard(
    request: focus_v1alpha1_pb.AddCardReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/addCard',
        request,
        metadata || {},
        this.methodDescriptoraddCard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/addCard',
    request,
    metadata || {},
    this.methodDescriptoraddCard);
  }

  methodDescriptorlistCards = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/listCards',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.ListCardReq,
    focus_v1alpha1_pb.ListCardResp,
    (request: focus_v1alpha1_pb.ListCardReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.ListCardResp.deserializeBinary
  );

  listCards(
    request: focus_v1alpha1_pb.ListCardReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.ListCardResp>;

  listCards(
    request: focus_v1alpha1_pb.ListCardReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListCardResp) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.ListCardResp>;

  listCards(
    request: focus_v1alpha1_pb.ListCardReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListCardResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/listCards',
        request,
        metadata || {},
        this.methodDescriptorlistCards,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/listCards',
    request,
    metadata || {},
    this.methodDescriptorlistCards);
  }

  methodDescriptorgetCard = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/getCard',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    focus_v1alpha1_pb.Card,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Card.deserializeBinary
  );

  getCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Card>;

  getCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Card>;

  getCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/getCard',
        request,
        metadata || {},
        this.methodDescriptorgetCard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/getCard',
    request,
    metadata || {},
    this.methodDescriptorgetCard);
  }

  methodDescriptorgetCards = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/getCards',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.GetCardReq,
    focus_v1alpha1_pb.GetCardResp,
    (request: focus_v1alpha1_pb.GetCardReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.GetCardResp.deserializeBinary
  );

  getCards(
    request: focus_v1alpha1_pb.GetCardReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.GetCardResp>;

  getCards(
    request: focus_v1alpha1_pb.GetCardReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.GetCardResp) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.GetCardResp>;

  getCards(
    request: focus_v1alpha1_pb.GetCardReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.GetCardResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/getCards',
        request,
        metadata || {},
        this.methodDescriptorgetCards,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/getCards',
    request,
    metadata || {},
    this.methodDescriptorgetCards);
  }

  methodDescriptorgetCardProgressSummary = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/getCardProgressSummary',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    focus_v1alpha1_pb.CardProgressSummaryResp,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.CardProgressSummaryResp.deserializeBinary
  );

  getCardProgressSummary(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.CardProgressSummaryResp>;

  getCardProgressSummary(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.CardProgressSummaryResp) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.CardProgressSummaryResp>;

  getCardProgressSummary(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.CardProgressSummaryResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/getCardProgressSummary',
        request,
        metadata || {},
        this.methodDescriptorgetCardProgressSummary,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/getCardProgressSummary',
    request,
    metadata || {},
    this.methodDescriptorgetCardProgressSummary);
  }

  methodDescriptorpatchCard = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/patchCard',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.PatchCardReq,
    focus_v1alpha1_pb.Card,
    (request: focus_v1alpha1_pb.PatchCardReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Card.deserializeBinary
  );

  patchCard(
    request: focus_v1alpha1_pb.PatchCardReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Card>;

  patchCard(
    request: focus_v1alpha1_pb.PatchCardReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Card>;

  patchCard(
    request: focus_v1alpha1_pb.PatchCardReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Card) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/patchCard',
        request,
        metadata || {},
        this.methodDescriptorpatchCard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/patchCard',
    request,
    metadata || {},
    this.methodDescriptorpatchCard);
  }

  methodDescriptorrerankCard = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/rerankCard',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.RankCardReq,
    google_protobuf_empty_pb.Empty,
    (request: focus_v1alpha1_pb.RankCardReq) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  rerankCard(
    request: focus_v1alpha1_pb.RankCardReq,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  rerankCard(
    request: focus_v1alpha1_pb.RankCardReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  rerankCard(
    request: focus_v1alpha1_pb.RankCardReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/rerankCard',
        request,
        metadata || {},
        this.methodDescriptorrerankCard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/rerankCard',
    request,
    metadata || {},
    this.methodDescriptorrerankCard);
  }

  methodDescriptordeleteCard = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/deleteCard',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteCard(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/deleteCard',
        request,
        metadata || {},
        this.methodDescriptordeleteCard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/deleteCard',
    request,
    metadata || {},
    this.methodDescriptordeleteCard);
  }

  methodDescriptorcreateLabel = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/createLabel',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.Label,
    focus_v1alpha1_pb.Label,
    (request: focus_v1alpha1_pb.Label) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Label.deserializeBinary
  );

  createLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Label>;

  createLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Label) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Label>;

  createLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Label) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/createLabel',
        request,
        metadata || {},
        this.methodDescriptorcreateLabel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/createLabel',
    request,
    metadata || {},
    this.methodDescriptorcreateLabel);
  }

  methodDescriptorlistLabels = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/listLabels',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.ListLabelsReq,
    focus_v1alpha1_pb.ListLabelsResp,
    (request: focus_v1alpha1_pb.ListLabelsReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.ListLabelsResp.deserializeBinary
  );

  listLabels(
    request: focus_v1alpha1_pb.ListLabelsReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.ListLabelsResp>;

  listLabels(
    request: focus_v1alpha1_pb.ListLabelsReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListLabelsResp) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.ListLabelsResp>;

  listLabels(
    request: focus_v1alpha1_pb.ListLabelsReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListLabelsResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/listLabels',
        request,
        metadata || {},
        this.methodDescriptorlistLabels,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/listLabels',
    request,
    metadata || {},
    this.methodDescriptorlistLabels);
  }

  methodDescriptorupdateLabel = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/updateLabel',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.Label,
    focus_v1alpha1_pb.Label,
    (request: focus_v1alpha1_pb.Label) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Label.deserializeBinary
  );

  updateLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Label>;

  updateLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Label) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Label>;

  updateLabel(
    request: focus_v1alpha1_pb.Label,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Label) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/updateLabel',
        request,
        metadata || {},
        this.methodDescriptorupdateLabel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/updateLabel',
    request,
    metadata || {},
    this.methodDescriptorupdateLabel);
  }

  methodDescriptordeleteLabel = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/deleteLabel',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteLabel(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteLabel(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteLabel(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/deleteLabel',
        request,
        metadata || {},
        this.methodDescriptordeleteLabel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/deleteLabel',
    request,
    metadata || {},
    this.methodDescriptordeleteLabel);
  }

  methodDescriptorlistChallenges = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/listChallenges',
    grpcWeb.MethodType.UNARY,
    focus_v1alpha1_pb.ListChallengesReq,
    focus_v1alpha1_pb.ListChallengesResp,
    (request: focus_v1alpha1_pb.ListChallengesReq) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.ListChallengesResp.deserializeBinary
  );

  listChallenges(
    request: focus_v1alpha1_pb.ListChallengesReq,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.ListChallengesResp>;

  listChallenges(
    request: focus_v1alpha1_pb.ListChallengesReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListChallengesResp) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.ListChallengesResp>;

  listChallenges(
    request: focus_v1alpha1_pb.ListChallengesReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.ListChallengesResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/listChallenges',
        request,
        metadata || {},
        this.methodDescriptorlistChallenges,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/listChallenges',
    request,
    metadata || {},
    this.methodDescriptorlistChallenges);
  }

  methodDescriptorgetChallenge = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.Focus/getChallenge',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.UInt64Value,
    focus_v1alpha1_pb.Challenge,
    (request: google_protobuf_wrappers_pb.UInt64Value) => {
      return request.serializeBinary();
    },
    focus_v1alpha1_pb.Challenge.deserializeBinary
  );

  getChallenge(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null): Promise<focus_v1alpha1_pb.Challenge>;

  getChallenge(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Challenge) => void): grpcWeb.ClientReadableStream<focus_v1alpha1_pb.Challenge>;

  getChallenge(
    request: google_protobuf_wrappers_pb.UInt64Value,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: focus_v1alpha1_pb.Challenge) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.Focus/getChallenge',
        request,
        metadata || {},
        this.methodDescriptorgetChallenge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.Focus/getChallenge',
    request,
    metadata || {},
    this.methodDescriptorgetChallenge);
  }

}

