name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: focus_test
          POSTGRES_USER: focus
          POSTGRES_PASSWORD: focus-passwd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - uses: actions/checkout@v3

      - name: Test
        run: make test
        env:
          FC_DATABASE_PASSWD: focus-passwd
